import Vue from 'vue'
import 'vant/lib/index.css'
import { Button, Tabbar, TabbarItem, Swipe, ContactCard, SwipeItem, Search, ActionSheet, Tab, Tabs, Rate, Lazyload, NoticeBar, Col, Row, Divider, Sidebar, SidebarItem, NavBar, Icon, GoodsAction, GoodsActionIcon, GoodsActionButton, SubmitBar, Checkbox, Grid, GridItem, Form, Field, Toast, Empty, Dialog } from 'vant'

Vue.use(Button)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Search)
Vue.use(Lazyload)
Vue.use(NoticeBar)
Vue.use(Col)
Vue.use(Row)
Vue.use(Divider)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(NavBar)
Vue.use(Icon)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(GoodsActionButton)
Vue.use(SubmitBar)
Vue.use(Checkbox)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Form)
Vue.use(Field)
Vue.use(Rate)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(ContactCard)
Vue.use(ActionSheet)
Vue.use(Empty)
Vue.use(Toast)
Vue.use(Dialog)
